In [1]:
# project 
# take data from mySql data base 
# model dump and integrate with backend 
# deploy the project

In [2]:
# project using mysql and joblib and slr

In [3]:
#!pip install mysql-connector-python

In [4]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
data ={
    'name':['mohit','dheeraj','yash','kunal'],
    'avg_income':[1000,200,300,400], 
    'house_age':[10.2,2.5,3.0,4.0],
    'num_rooms':[3,4,5,1], 
    'price':[10000,7000,15000,11000]
}
df=pd.DataFrame(data)
df

      name  avg_income  house_age  num_rooms  price
0    mohit        1000       10.2          3  10000
1  dheeraj         200        2.5          4   7000
2     yash         300        3.0          5  15000
3    kunal         400        4.0          1  11000

In [5]:
# handle missing values 
# df.drop('name',axis=1,inplace=True)
# feature scaling 
scaler=StandardScaler()
df[['avg_income','house_age','num_rooms']]=scaler.fit_transform(df[['avg_income','house_age','num_rooms']])
df

      name  avg_income  house_age  num_rooms  price
0    mohit    1.686761   1.705444  -0.169031  10000
1  dheeraj   -0.883541  -0.784019   0.507093   7000
2     yash   -0.562254  -0.622366   1.183216  15000
3    kunal   -0.240966  -0.299059  -1.521278  11000

In [6]:
# split data 
X=df[['avg_income','house_age','num_rooms']]
y=df['price']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:
# model train 
model=LinearRegression()
model.fit(x_train,y_train)
# prediction 
new_data=pd.DataFrame({
    "avg_income":[200],
    "house_age":[8],
    "num_rooms":[4]
})
# feature_scaling
new_data[['avg_income','house_age','num_rooms']]=scaler.fit_transform(new_data[['avg_income','house_age','num_rooms']])
predict_data=model.predict(new_data)
print(predict_data[0])

8496.575851006844

In [8]:
# model dump 
#!pip install joblib
import joblib
joblib.dump(model,"house_predict.joblib")

['house_predict.joblib']

In [9]:
# mysql connection 
# mysql connector
# !pip install pymysql cryptography
import pymysql
conn = pymysql.connect(host="13.220.156.88",user="mluser",database="ml_db",password="mlpass123")
print(conn)
query = "select avg_income,house_age,num_rooms,price,name from houses"
df = pd.read_sql(query,conn)
print(df)

OperationalError: (2003, "Can't connect to MySQL server on '13.220.156.88' (timed out)")

In [ ]:
# from sqlalchemy import create_engine

# engine = create_engine(
#     "mysql+mysqlconnector://mluser:mlpass123@13.220.156.88/ml_db"
# )

# try:
#     with engine.connect() as conn:
#         print("Connection Successful")
# except Exception as e:
#     print(e)

In [ ]:
# from sqlalchemy import create_engine
# import pandas as pd

# engine = create_engine("mysql+mysqlconnector://mluser:mlpass123@13.220.156.88/ml_db")

# query = "SELECT avg_income, house_age, num_rooms, price FROM houses"

# df2 = pd.read_sql(query, engine)

# print(df2.head())